name: Health Check

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check API is up
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ secrets.ANECDOTES_API_URL }}/anecdotes
          follow-redirect: true
          max-attempts: 3
          retry-delay: 5s
          timeout: 30s
          retry-all: true
